### ISSUE TITLE
Not working for Mac

### ISSUE THREAD

**Issue by sartaj10** [manojmj92/subtitle-downloader#18] opened 2015-09-25 14:32 UTC
Hi

Trying to run it on a mac but I'm not able to.
I've added the script in "Services" but can't see it when I right click

Please resolve

**Comment by ryangu** [comment] 2015-10-29 16:46
I have the same problem, it's not working on mac, please fix it.

**Comment by ryangu** [comment] 2015-10-29 18:25
Finally, I figured out where the problem is. You should add a "Get Selected Finder Items" workflow in "File&Folders" before the Run Shell Script. Make sure that Services receives type is "no input". good luck

**Comment by padfootzhub** [comment] 2016-01-29 04:27
Guess am not the only one running into it.. ;) This is now fixed by adding a step in the README. Commit: [bd7b3ff101c18c79fca322364bd14b2b76b2aa57](https://github.com/manojmj92/subtitle-downloader/commit/bd7b3ff101c18c79fca322364bd14b2b76b2aa57)

**Closed** 2016-03-31 08:36 UTC
